### ISSUE TITLE
Holdeover Transposed "Hepheastus"

### ISSUE THREAD

**Issue by skamortuus** [Eldritchdraaks/Denizen-Themes#1]
[I've never used github before and I definitely have very limited computer knowledge - my apologies if this is not the place where this sort of inquiry goes.]

This is a wholly minor thing with the otherwise perfectly lovely mod, but while the folder for the assets and the files contained therein all use the (correctly spelt) "Hephaestus", in the mod description portion in mod.js file, the A and E transposed "Hapheastus" is used instead, thereby failing to bring up the Preview image when clicked:

"<a href=\"assets://archive/collection/Hepheastus/hepheastus_preview.png\">Hepheastus</a>"

This doesn't affect any of the real functionality, but I thought you'd want to know?

**Comment by Eldritchdraaks** [comment]
Thanks for pointing this out, I've made the fix and uploaded v1.2 of the mod.js file.
